export const GET_CARTS_DATA = 'detail@get_carts_data'
export const SET_ITEM_CHECKED = 'detail@set_item_checked'
export const SET_ITEM_COUNT = 'detail@set_item_count'
export const SET_CHOICES = 'detail@set_choices'
export const DELETE_CHOICES = 'detail@delete_choices'